### ISSUE TITLE
您好，请教一下关于量化的问题。

### ISSUE THREAD

**Issue by infrontofme** [venturezhao/XJTU-Tripler#4]
感谢分享你们的工作！请问下图上公式(2)是表示什么意思？是如何使用的？
![image](https://user-images.githubusercontent.com/34626896/90600978-08a8b780-e22a-11ea-8fda-8cbdfa00579b.png)

**Comment by venturezhao** [comment]
您好，这是我们最初的量化方案，掉点有点多。
公式2表示我们采用的是2的幂次方进行量化，即，将fm或wt按照2的幂次放扩大到signed char的表示范围。

**Comment by infrontofme** [comment]
所以output里的ratio是基于公式1得到的吗？

**Comment by venturezhao** [comment]
> 所以output里的ratio是基于公式1得到的吗？

这一版方案，是的。
之后的方案里，不再直接使用最值作为限定，而是选择一定合适的范围进行量化，参见NVIDIA tensor RT的做法。
再后来，我们做逐channel量化了，不再拘泥于每一层统一一个clip值。

**Comment by infrontofme** [comment]
好的，感谢~那你们使用量化方案有微调这一步骤吗？是如何实现的？

**Comment by infrontofme** [comment]
在推理过程中，那每一层output输出是整型还是浮点型呢？作为下一层输入时是要量化成INT8再输入下一层吗？

**Comment by venturezhao** [comment]
> 在推理过程中，那每一层output输出是整型还是浮点型呢？作为下一层输入时是要量化成INT8再输入下一层吗？

我们完全是int8的，如果激活函数是sigmoid，会适当放宽到9-10bit。
每一层转成浮点是没有必要的，因为你再往后还要定点化的。全网络直接从头到尾都是定点的。

**Comment by infrontofme** [comment]
好的，感谢。那就是卷积参数和输入量化到INT8后，按照上图output的公式得到的结果应该是浮点型的然后也按照这个量化流程处理那中间不会产生INT16或者浮点数的中间值吗？按照NVIDIA的方案，每一层的ratio值得到的是浮点数然后乘以输入再按照(4)和(3)量化到INT8，所以你们在这里处理的时候是把ratio全部取整了吗？那你们中间没有在线量化的过程吗？

那在正式推理过程中，很好理解权值都是INT8的，对于新输入的图像，按照这种方式量化到INT8后输入到网络里，经过卷积和激活函数后得到的output不也是需要再在线进行量化的吗？

有点没太理解，感谢您的耐心解答！

**Comment by venturezhao** [comment]
> 好的，感谢。那就是卷积参数和输入量化到INT8后，按照上图output的公式得到的结果应该是浮点型的然后也按照这个量化流程处理那中间不会产生INT16或者浮点数的中间值吗？按照NVIDIA的方案，每一层的ratio值得到的是浮点数然后乘以输入再按照(4)和(3)量化到INT8，所以你们在这里处理的时候是把ratio全部取整了吗？那你们中间没有在线量化的过程吗？
> 
> 那在正式推理过程中，很好理解权值都是INT8的，对于新输入的图像，按照这种方式量化到INT8后输入到网络里，经过卷积和激活函数后得到的output不也是需要再在线进行量化的吗？
> 
> 有点没太理解，感谢您的耐心解答！

这也就是量化参数对神经网络泛化的影响。如果换了新的图像，重跑一遍量化算法的话，得到的每一层的缩放系数有很大概率是与之前不一样的。因此只能是选择跑完一组finetune样本后平均准确率最高的一组参数作为最终的选择。
当然量化是我们隔壁组做的，不知道现在有没有什么新的发展[doge]

**Comment by infrontofme** [comment]
好的感谢，按照上述量化公式算出来的output是整数还是小数？你们在FPGA内部要做除法操作吗？

**Comment by venturezhao** [comment]
> 好的感谢，按照上述量化公式算出来的output是整数还是小数？你们在FPGA内部要做除法操作吗？

都是定点数，整数或小数取决于Q值法时，小数点的位置。FPGA不做除法，FPGA除法效率很低，如果我没记错的话，32bit除法要20几个周期。
