### ISSUE TITLE
赵老师您好，hpu_core中的mpu和vpu是闭源网表文件，有没有对这两个模块的接口或者模块详细说明？

### ISSUE THREAD

**Issue by retina007** [venturezhao/XJTU-Tripler#6]
或者能否对当初参赛版本的文件开源。（现在应该更新好几个版本了吧？）
谢谢回复

**Comment by venturezhao** [comment]
抱歉抱歉，这部分没有开源。
建议学习的话，以NVDLA为蓝本进行学习。这个版本的资料比较全。

**Comment by retina007** [comment]
谢谢。。。
好的，查看资料，看了一下大概理解了“乘加”的方法原理。
我还有一个问题，我新弄提了个issue，关于vpu_ctrl.v模块。

**Comment by retina007** [comment]
> 抱歉抱歉，这部分没有开源。
> 建议学习的话，以NVDLA为蓝本进行学习。这个版本的资料比较全。

谢谢。。。
好的，查看资料，看了一下大概理解了“乘加”的方法原理。
我还有一个问题，我新弄提了个issue，关于vpu_ctrl.v模块。
