### ISSUE TITLE
关于vpu_ctrl.v模块中clip，prot是什么操作

### ISSUE THREAD

**Issue by retina007** [venturezhao/XJTU-Tripler#7]
clip是裁剪/剪枝吗？（Pruning）
prot是什么操作。
应该参考哪些资料。
![vpu](https://user-images.githubusercontent.com/15125380/111295578-803aaa00-8686-11eb-81ff-84b9cdc4db7d.JPG)

**Comment by venturezhao** [comment]
您好，Pruning操作是在网络部署在硬件之前就已经完成的，所以这里的clip是对MAC计算结果的re-quantization的过程。prot是之前起的名字，用作数据溢出保护，应该称之为saturation。

硬件设计人员一般根据算法的需求就可以直接设计了。不需要参考什么文档的。
